---
galaxy_info:
  author: Joep Goossens
  description: Run the POST-patch tasks and checks.

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: "EL"
      versions:
        - "8"

  galaxy_tags: []

dependencies: []
