---
- name: Check and sanitize input
  hosts: '{{target|default("all")}}'
  connection: local
  become: false
  gather_facts: false
  roles:
    - jgoos.patch_workflow.sanitize_input

# - FQDN's uit de survey opschonen
# - Werkende FQDN
# - Zit de FQDN in de dynamic inventory
# Misschien al een ping uitvoeren op de machines voor de zekerheid?
